#数据源配置
spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.110.110:3306/chinaboy_boot?useUnicode=yes&characterEncoding=UTF8&useSSL=false
  username: chinaboy
  password: chinaboy
  initialSize: 1
  minIdle: 1
  maxActive: 20
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: select 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxOpenPreparedStatements: 20
#mybatis配置
mybatis:
 type-aliases-package: com.mss.boot.entity
 mapper-locations: classpath:mapper/map*.xml