--Demon表
CREATE TABLE `DEMO` (
  `ID` INT(11) DEFAULT NULL,
  `AMOUNT` DECIMAL(15,2) DEFAULT NULL,
  `REMARK` VARCHAR(32) DEFAULT NULL,
  `CREATEDATE` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;